// packages/ffan-scripts/_commons/page/vue/default/App.vue
<style>

  .footer {
    border  : 1px solid darkcyan; /*no*/
    padding : 20px;
  }

  .hl {
    color : #00aeff;
  }

</style>

<template>
  <div class="app">
    <h1>Hello <span class="hl"> {{name}}</span></h1>
    <img src="./assets/images/ffan.jpg" alt="ffan">
    <div class="footer">Footer</div>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        name: 'World'
      }
    }
  }
</script>

// packages/ffan-scripts/commons/boilerplate/react/default/App.js
import React, {Component} from 'react'
import './assets/index.less'

export default class App extends Component {
  render() {
    return <div>
      <h1>Hello
        <span className="highLight"> {this.props.name}</span>
        </h1>
      <img src={require('./assets/images/ffan.jpg')} alt="飞凡"/>
    </div>
  }
}
